default_docker_ip: "172.17.42.1"
bahmni_user: bahmni
bahmni_group: bahmni

metabase_db_user: metabase
metabase_db_name: metabase
metabase_db_password: "{{metabase_db_password}}"
metabase_port: 9003
metabase_db_type: postgres
metabase_db_port: 5432
metabase_db_server: "{{ groups['metabase-db'][0] | default(default_docker_ip, true) }}"
metabase_docker_compose_location: "/opt/bahmni-mart/metabase-docker-compose.yml"
metabase_docker_image: "metabase/metabase:latest"
metabase_docker_container_name: metabase
postgres_version: 9.6
