- name: Check if docker-io present
  yum:
    list: docker-io
  register: docker_info
  ignore_errors: true

- name: Uninstall docker-io
  yum:
    name: docker-io
    state: absent
  when: docker_info.results|length != 0

- name: Check if docker-engine needs an update
  yum:
    list: docker-engine
  register: docker_engine_info
  ignore_errors: true

- name: Uninstall docker-engine
  yum:
    name: docker-engine
    state: absent
  when: docker_engine_info.results|length != 0 and docker_engine_info.results[0].version != "{{ docker_version }}"

- name: Install docker-io
  command: yum install -y https://s3.ap-south-1.amazonaws.com/bahmni-mart/docker-io/docker-io-1.7.1-2.el6.x86_64.rpm
  when: docker_engine_info.results|length == 0 or docker_engine_info.results[0].version != "{{ docker_version }}"

- name: Evaluate docker compose url
  shell: "echo {{ docker_compose_url }}"
  register: evaluated_docker_compose_url

- name: Install docker-compose
  get_url:
    url: "{{ evaluated_docker_compose_url.stdout }}"
    dest: /usr/bin/docker-compose
    mode: 0755

- name: Start docker and enabled at boot
  service:
    name: docker
    enabled: yes
    state: started